import { existsSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

const MARKER_START = '# >>> dw-kit managed >>>';
const MARKER_END = '# <<< dw-kit managed <<<';

const DW_GITIGNORE_BLOCK = [
  MARKER_START,
  '# dw-kit framework files — regenerated by `dw init` / `dw upgrade`.',
  '# Do NOT commit. Update dw-kit regularly via `dw upgrade`.',
  'adapters/',
  'core/',
  'security/',
  '',
  '# Config directory: ignore framework files, keep user dw.config.yml tracked',
  'config/*',
  '!config/dw.config.yml',
  '!config/.gitignore',
  'config/dw.config.local.yml',
  '',
  '# Local-only telemetry (machine-specific, has session hashes)',
  'metrics/',
  MARKER_END,
];

const CLAUDE_GITIGNORE_BLOCK = [
  MARKER_START,
  '# dw-kit framework files — regenerated by `dw init` / `dw upgrade`.',
  '# Do NOT commit. Update dw-kit regularly via `dw upgrade`.',
  'agents/',
  'hooks/',
  'rules/',
  'skills/',
  'templates/',
  '',
  '# Local-only override (also in root .gitignore for safety)',
  'settings.local.json',
  MARKER_END,
];

function ensureDir(filepath) {
  const dir = dirname(filepath);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
}

function applyManagedBlock(content, blockLines) {
  const block = blockLines.join('\n') + '\n';
  if (!content) return block;

  // If markers already present, replace block in-place (idempotent + upgrade-friendly)
  const startIdx = content.indexOf(MARKER_START);
  const endIdx = content.indexOf(MARKER_END);
  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    const before = content.slice(0, startIdx);
    const after = content.slice(endIdx + MARKER_END.length);
    return (before + block + after).replace(/\n{3,}/g, '\n\n');
  }

  // Markers not present — append block
  const sep = content.endsWith('\n') ? '\n' : '\n\n';
  return content + sep + block;
}

function writeGitignore(targetPath, blockLines) {
  ensureDir(targetPath);
  const current = existsSync(targetPath) ? readFileSync(targetPath, 'utf-8') : '';
  const updated = applyManagedBlock(current, blockLines);
  if (updated === current) return { action: 'noop', path: targetPath };
  writeFileSync(targetPath, updated, 'utf-8');
  return { action: current ? 'updated' : 'created', path: targetPath };
}

export function ensureDwGitignore(projectDir = process.cwd()) {
  return writeGitignore(join(projectDir, '.dw', '.gitignore'), DW_GITIGNORE_BLOCK);
}

export function ensureClaudeGitignore(projectDir = process.cwd()) {
  return writeGitignore(join(projectDir, '.claude', '.gitignore'), CLAUDE_GITIGNORE_BLOCK);
}

export function ensureBothGitignores(projectDir = process.cwd()) {
  return {
    dw: ensureDwGitignore(projectDir),
    claude: ensureClaudeGitignore(projectDir),
  };
}
