#!/bin/bash
# scripts/migrate-v03-to-v2.sh
# Migrate project từ dw-kit v0.3 sang v2
# Usage: bash scripts/migrate-v03-to-v2.sh [--dry-run]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

DRY_RUN=false
[ "${1:-}" = "--dry-run" ] && DRY_RUN=true

log()  { echo "  $*"; }
info() { echo ""; echo "▶ $*"; }
warn() { echo "  ⚠  $*"; }
ok()   { echo "  ✓  $*"; }
dry()  { [ "$DRY_RUN" = true ] && echo "  [dry] $*" || true; }
do_action() {
  if [ "$DRY_RUN" = true ]; then echo "  [dry] $*"; else eval "$*"; fi
}

OLD_CONFIG="$PROJECT_ROOT/dv-workflow.config.yml"
NEW_CONFIG_DIR="$PROJECT_ROOT/config"
NEW_CONFIG="$NEW_CONFIG_DIR/dw.config.yml"

echo ""
echo "══════════════════════════════════════════"
echo "  dw-kit v0.3 → v2 Migration"
[ "$DRY_RUN" = true ] && echo "  Mode: DRY RUN"
echo "══════════════════════════════════════════"

# ── Step 1: Validate v0.3 present ────────────────────────────────────────────
info "Step 1: Validate source config"

if [ ! -f "$OLD_CONFIG" ]; then
  echo "  No dv-workflow.config.yml found. Already on v2 or fresh install."
  exit 0
fi

if [ -L "$OLD_CONFIG" ]; then
  warn "dv-workflow.config.yml is already a symlink → migration may have already run."
  read -r -p "  Continue anyway? [y/N] " confirm
  [[ "$confirm" =~ ^[Yy]$ ]] || exit 0
fi

ok "Found dv-workflow.config.yml"

# ── Step 2: Detect customized skills ─────────────────────────────────────────
info "Step 2: Detect customized skills"

OVERRIDES_DIR="$PROJECT_ROOT/adapters/claude-cli/overrides/skills"
SKILLS_DIR="$PROJECT_ROOT/.claude/skills"
customized_count=0

# Heuristic: compare với toolkit's own copy nếu có, hoặc check git
if command -v git &>/dev/null && git -C "$PROJECT_ROOT" rev-parse --git-dir &>/dev/null; then
  for skill_dir in "$SKILLS_DIR"/*/; do
    [ -d "$skill_dir" ] || continue
    skill_name=$(basename "$skill_dir")
    skill_file="$skill_dir/SKILL.md"
    [ -f "$skill_file" ] || continue

    # Check if file was modified from its committed version
    if ! git -C "$PROJECT_ROOT" diff --quiet HEAD -- ".claude/skills/$skill_name/SKILL.md" 2>/dev/null; then
      warn "Skill '$skill_name' has uncommitted changes → preserving to overrides/"
      do_action "mkdir -p '$OVERRIDES_DIR/$skill_name'"
      do_action "cp '$skill_file' '$OVERRIDES_DIR/$skill_name/SKILL.md'"
      customized_count=$((customized_count + 1))
    fi
  done
else
  warn "Not a git repo or git not available. Cannot auto-detect customizations."
  warn "Manually copy customized skills to adapters/claude-cli/overrides/skills/ before upgrading."
fi

if [ $customized_count -gt 0 ]; then
  ok "$customized_count customized skill(s) preserved to overrides/"
else
  ok "No customized skills detected"
fi

# ── Step 3: Migrate config ────────────────────────────────────────────────────
info "Step 3: Migrate config (dv-workflow.config.yml → config/dw.config.yml)"

if [ -f "$NEW_CONFIG" ]; then
  warn "config/dw.config.yml already exists. Skipping config migration."
  warn "Review manually: $NEW_CONFIG"
else
  if ! command -v python3 &>/dev/null; then
    warn "python3 not found. Manual config migration needed."
    warn "Map: level: 1 → default_depth: quick"
    warn "     level: 2 → default_depth: standard"
    warn "     level: 3 → default_depth: thorough"
  else
    if [ "$DRY_RUN" = false ]; then
      mkdir -p "$NEW_CONFIG_DIR"
      python3 - "$OLD_CONFIG" "$NEW_CONFIG" <<'PYEOF'
import sys, re

old_path = sys.argv[1]
new_path = sys.argv[2]

with open(old_path) as f:
    old_content = f.read()

# Extract values from old config
def get_val(key, content, default=""):
    m = re.search(rf'^\s*{re.escape(key)}:\s*([^\n#]+)', content, re.MULTILINE)
    if m:
        return m.group(1).strip().strip('"').strip("'")
    return default

project_name = get_val("name", old_content, "my-project")
project_lang = get_val("language", old_content, "vi")
level_str    = get_val("level", old_content, "2")

depth_map = {"1": "quick", "2": "standard", "3": "thorough"}
depth = depth_map.get(level_str, "standard")

# Extract roles
roles_match = re.findall(r'^\s+-\s+(dev|techlead|ba|qc|pm)\b', old_content, re.MULTILINE)
roles = roles_match if roles_match else ["dev"]

# Extract quality commands
test_cmd = get_val("test_command", old_content, "")
lint_cmd  = get_val("lint_command", old_content, "")

# Extract paths
tasks_path   = get_val("tasks", old_content, ".dw/tasks")
docs_path    = get_val("docs", old_content, ".dw/docs")

# Build new config
roles_yaml = "\n".join(f"    - {r}" for r in roles)

new_config = f"""# dw-kit Configuration
# Generated by migrate-v03-to-v2.sh
# Review and adjust as needed.

project:
  name: "{project_name}"
  language: "{project_lang}"

workflow:
  default_depth: "{depth}"   # quick | standard | thorough
  # AI assesses per-task and may recommend different depth

team:
  roles:
{roles_yaml}

quality:
  test_command: "{test_cmd}"   # empty = skip
  lint_command: "{lint_cmd}"   # empty = skip
  block_on_fail: false

tracking:
  estimation: false
  log_work: false
  estimation_unit: "hours"

paths:
  tasks: "{tasks_path}"
  docs: "{docs_path}"

# Claude-specific capabilities (Layer 2)
claude:
  models:
    plan: ""          # empty = inherit from Claude Code settings
    execute: ""
    review: ""
  structured_output: true
  worktree_execution: false
  mcp: []

# Toolkit version tracking (do not edit manually)
_toolkit:
  core_version: "2.0"
  platform_version: "1.0"
  capability_version: "1.0"
  migrated_from: "v0.3"
  last_upgrade: "{__import__('datetime').date.today().isoformat()}"
"""

with open(new_path, 'w') as f:
    f.write(new_config)
PYEOF
      ok "config/dw.config.yml created (migrated from level: $level_str → depth: $(grep default_depth "$NEW_CONFIG" | head -1))"
    else
      dry "Would create config/dw.config.yml from dv-workflow.config.yml"
    fi
  fi
fi

# ── Step 4: Create backward-compat symlink ────────────────────────────────────
info "Step 4: Create backward-compat symlink"

if [ -f "$NEW_CONFIG" ] && [ ! -L "$OLD_CONFIG" ]; then
  if [ "$DRY_RUN" = false ]; then
    # Backup original
    cp "$OLD_CONFIG" "${OLD_CONFIG}.bak"
    ok "Backed up original to dv-workflow.config.yml.bak"
    # Create symlink
    rm "$OLD_CONFIG"
    ln -s "config/dw.config.yml" "$OLD_CONFIG"
    ok "Created symlink: dv-workflow.config.yml → config/dw.config.yml"
  else
    dry "Would create symlink: dv-workflow.config.yml → config/dw.config.yml"
  fi
fi

# ── Step 5: Check CI/CD references ───────────────────────────────────────────
info "Step 5: Check CI/CD references"

found_refs=false
for ci_file in ".github/workflows/"*.yml ".gitlab-ci.yml" "Makefile" ".circleci/config.yml" "package.json"; do
  full_path="$PROJECT_ROOT/$ci_file"
  if [ -f "$full_path" ]; then
    if grep -qE "dv-workflow\.config\.yml|dv-workflow-kit" "$full_path" 2>/dev/null; then
      warn "Found reference in: $ci_file — update to config/dw.config.yml"
      found_refs=true
    fi
  fi
done
[ "$found_refs" = false ] && ok "No CI/CD references found"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "══════════════════════════════════════════"
if [ "$DRY_RUN" = true ]; then
  echo "  DRY RUN complete. Review above, then run without --dry-run."
else
  echo "  Migration complete!"
  echo ""
  echo "  Next steps:"
  echo "  1. Review config/dw.config.yml — adjust team.roles, quality commands"
  echo "  2. Run: bash setup.sh to regenerate .claude/ from new config"
  echo "  3. Check adapters/claude-cli/overrides/ for preserved customizations"
  [ "$found_refs" = true ] && echo "  4. ⚠  Update CI/CD files (see warnings above)"
fi
echo "══════════════════════════════════════════"
echo ""
